import type {GameContent,ItemDefinition,ExpeditionKind} from '../../core/content-r3.ts';
import type {GameState} from '../../core/game-core-r3.ts';
type Hero=GameState['heroes'][number];
const esc=(value:unknown)=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export interface ItemChoice {itemId:string;slot:0|1|null}
export interface RewardChoice extends ItemChoice {rewardId:string}
export const destinationIcon=(kind:ExpeditionKind)=>({camp:'◆',shop:'✦',roshan:'♜'})[kind];
export const itemIcon=(item:ItemDefinition)=>({additional_target:'✦',cooldown_reduction:'◷',detection:'◉',healing_aura:'✚'})[item.behaviorId];
export function itemLabel(content:GameContent,id:string|null){return id?content.items.find(item=>item.id===id)?.label??'Неизвестный предмет':'Пустой слот';}
export function itemDescription(item:ItemDefinition){return ({additional_target:`Дополнительная цель автоатаки. Не более ${item.maxTargets} целей.`,cooldown_reduction:`Перезарядка короче на ${item.magnitude}%.`,detection:`Обнаруживает скрытых врагов в радиусе ${item.radius}.`,healing_aura:`Лечит ${item.magnitude} HP каждые ${(item.intervalTicks/30).toFixed(1)} с в радиусе ${item.radius}.`})[item.behaviorId];}
export function expeditionReward(content:GameContent,kind:ExpeditionKind){const d=content.expeditions.find(e=>e.kind===kind)!;return kind==='camp'?`${d.goldReward} золота`:kind==='shop'?'Один предмет на выбор после возвращения':'Aegis: одно воскрешение отправленного героя';}
export function heroStateText(content:GameContent,hero:Hero){return hero.expedition?`${content.expeditions.find(e=>e.kind===hero.expedition!.kind)?.label} · ${Math.ceil(hero.expedition.remainingTicks/30)} с`:hero.hp>0?`${hero.hp}/${hero.maxHp} HP`:`Возвращение ${Math.ceil(hero.respawnTicks/30)} с`;}
export function inventoryHtml(content:GameContent,hero:Hero){return `<div class="inventory" aria-label="Предметы ${esc(hero.kind)}"><p class="section-label">Два слота предметов</p><div class="item-slots">${hero.items.map((id,slot)=>{const item=content.items.find(i=>i.id===id);return `<div class="item-slot${item?' occupied':''}" data-slot="${slot}"><span class="item-icon" aria-hidden="true">${item?itemIcon(item):'＋'}</span><div><small>Слот ${slot+1}</small><strong>${esc(itemLabel(content,id))}</strong>${item?`<p>${esc(itemDescription(item))}</p>`:''}</div></div>`;}).join('')}</div><div class="aegis-slot${hero.aegisToken?' active':''}" role="status"><span aria-hidden="true">♜</span><div><strong>${hero.aegisToken?'Aegis готов':'Aegis · пусто'}</strong><small>${hero.aegisToken?'Одно воскрешение только этого героя.':'Отдельная награда Рошана; не занимает предметный слот.'}</small></div></div></div>`;}
function slotButtons(content:GameContent,hero:Hero,choice:ItemChoice,action:string,rewardId?:string){return `<div class="slot-choices">${([0,1] as const).map(slot=>`<button class="subtle${choice.slot===slot?' selected':''}" data-action="${action}" data-slot="${slot}" ${rewardId?`data-reward="${esc(rewardId)}"`:''} data-focus="${action}-${rewardId??hero.id}-${slot}">${hero.items[slot]?`Заменить слот ${slot+1}`:`В слот ${slot+1}`}<small>${esc(itemLabel(content,hero.items[slot]))}</small></button>`).join('')}</div>`;}
function replacementText(content:GameContent,hero:Hero,choice:ItemChoice){return choice.slot!==null&&hero.items[choice.slot]?`Заменить «${itemLabel(content,hero.items[choice.slot])}» на «${itemLabel(content,choice.itemId)}». Старый предмет будет утрачен.`:`Получить «${itemLabel(content,choice.itemId)}» в слот ${(choice.slot??0)+1}.`;}
export function itemPurchaseHtml(content:GameContent,game:GameState,hero:Hero,choice:ItemChoice|null){
 if(game.phase!=='preparation'||hero.expedition||hero.hp<=0)return '<p class="small muted">Покупка предметов — между волнами, когда герой на позиции.</p>';
 const selected=choice&&content.items.find(i=>i.id===choice.itemId);return `<details class="item-shop" ${choice?'open':''}><summary>Купить предмет за золото</summary><div class="stack">${content.items.map(item=>{const compatible=item.compatibleHeroes.includes(hero.kind);const duplicate=hero.items.some(id=>content.items.find(i=>i.id===id)?.behaviorId===item.behaviorId);return `<button class="item-offer${choice?.itemId===item.id?' selected':''}" data-action="item-preview" data-item="${esc(item.id)}" data-focus="item-${item.id}" ${!compatible||duplicate?'disabled':''}><span class="item-icon" aria-hidden="true">${itemIcon(item)}</span><span><strong>${esc(item.label)}</strong><small>${esc(itemDescription(item))}</small><em>${item.cost} золота${!compatible?' · не подходит герою':duplicate?' · эффект уже экипирован':''}</em></span></button>`;}).join('')}${selected&&choice?`<div class="item-confirm"><p class="small">Выберите слот. Покупка требует подтверждения.</p>${slotButtons(content,hero,choice,'item-slot')}${choice.slot!==null?`<p class="small">${esc(replacementText(content,hero,choice))}</p><button class="gold" data-action="item-confirm" data-focus="item-confirm" ${game.gold<selected.cost?'disabled':''}>${hero.items[choice.slot]?'Подтвердить замену':'Подтвердить покупку'} · ${selected.cost} золота</button>${game.gold<selected.cost?'<p class="small error-copy">Не хватает золота.</p>':''}`:''}<button class="subtle" data-action="item-cancel">Отменить выбор</button></div>`:''}</div></details>`;
}
export function expeditionHtml(content:GameContent,game:GameState,hero:Hero,kind:ExpeditionKind|null){
 if(hero.expedition){let e=hero.expedition;return `<div class="expedition-status ${e.kind}" role="status"><strong>${esc(content.expeditions.find(d=>d.kind===e.kind)?.label)}</strong><p>Герой отсутствует в обороне. Позиция зарезервирована.</p><progress max="${e.totalTicks}" value="${e.totalTicks-e.remainingTicks}" aria-label="Ход вылазки"></progress><p>${Math.ceil(e.remainingTicks/30)} с боевого времени до возвращения.<br>${game.phase==='wave'?'Вылазка идёт.':'Таймер продолжится во время следующей волны.'}</p></div>`;}
 if(game.phase!=='preparation'||hero.hp<=0)return '<p class="small muted">Отправление в вылазку доступно между волнами.</p>';
 const busy=game.heroes.some(h=>h.expedition);const selected=kind&&content.expeditions.find(d=>d.kind===kind);return `<details class="expedition-menu" ${kind?'open':''}><summary>Отправить в вылазку</summary><div class="destination-choices">${content.expeditions.map(d=>`<button class="destination-choice ${d.kind}${kind===d.kind?' selected':''}" data-action="expedition-preview" data-kind="${d.kind}" data-focus="expedition-${d.kind}" ${busy||d.kind==='roshan'&&hero.aegisToken?'disabled':''}><span aria-hidden="true">${destinationIcon(d.kind)}</span><strong>${esc(d.label)}</strong><small>${d.durationTicks/30} с · ${esc(expeditionReward(content,d.kind))}</small></button>`).join('')}</div>${busy?'<p class="small muted">Другой герой уже в вылазке. Одновременно доступна одна.</p>':''}${selected?`<div class="expedition-confirm ${selected.kind}"><strong>${esc(selected.label)} · ${selected.durationTicks/30} с</strong><p>Награда: ${esc(expeditionReward(content,selected.kind))}.</p><p><strong>${esc(content.heroes.find(h=>h.kind===hero.kind)?.label)}</strong> уйдёт со своей позиции и не будет защищать Древнего. Таймер идёт только во время боя. Возвращение автоматическое.</p><button class="primary" data-action="expedition-confirm" data-focus="expedition-confirm" ${busy?'disabled':''}>Подтвердить отправление</button><button class="subtle" data-action="expedition-cancel">Отмена</button></div>`:''}</details>`;
}
export function pendingRewardsHtml(content:GameContent,game:GameState,choice:RewardChoice|null,discardId:string|null){return game.pendingRewards.map(reward=>{
 const hero=game.heroes.find(h=>h.id===reward.heroId)!;const selected=choice?.rewardId===reward.id?choice:null;return `<section class="reward-card" aria-label="Выбор награды" data-reward="${esc(reward.id)}"><p class="section-label">Награда тайной лавки</p><h3>${esc(content.heroes.find(d=>d.kind===hero.kind)?.label)}</h3><p class="small">Выберите предмет и слот. Награда сохранится до решения; следующая волна ждёт.</p>${game.phase!=='preparation'?'<p class="small muted">Завершите текущую волну, чтобы подтвердить выбор.</p>':''}${inventoryHtml(content,hero)}<div class="stack reward-options">${reward.options.map(id=>{const item=content.items.find(i=>i.id===id)!;const duplicate=hero.items.some(id=>content.items.find(i=>i.id===id)?.behaviorId===item.behaviorId);const compatible=item.compatibleHeroes.includes(hero.kind);return `<button class="item-offer${selected?.itemId===id?' selected':''}" data-action="reward-item" data-reward="${esc(reward.id)}" data-item="${esc(id)}" data-focus="reward-item-${reward.id}-${id}" ${!compatible||duplicate?'disabled':''}><span class="item-icon" aria-hidden="true">${itemIcon(item)}</span><span><strong>${esc(item.label)}</strong><small>${esc(itemDescription(item))}</small><em>${!compatible?'Не подходит герою':duplicate?'Эффект уже есть':'Бесплатная награда'}</em></span></button>`;}).join('')}</div>${selected?`${slotButtons(content,hero,selected,'reward-slot',reward.id)}${selected.slot!==null?`<p class="small">${esc(replacementText(content,hero,selected))}</p><button class="primary" data-action="reward-confirm" data-reward="${esc(reward.id)}" data-focus="reward-confirm-${reward.id}" ${game.phase!=='preparation'?'disabled':''}>${hero.items[selected.slot]?'Подтвердить замену':'Забрать в выбранный слот'}</button>`:''}`:''}${discardId===reward.id?`<p class="small error-copy">Отказ навсегда удалит эту награду без компенсации.</p><button class="danger" data-action="reward-discard-confirm" data-reward="${esc(reward.id)}" ${game.phase!=='preparation'?'disabled':''}>Подтвердить отказ от награды</button><button class="subtle" data-action="reward-discard-cancel">Сохранить выбор на потом</button>`:`<button class="subtle" data-action="reward-discard" data-reward="${esc(reward.id)}">Отказаться от награды…</button>`}</section>`;
 }).join('');}
